Repository dhshin1125/algorithm_study, pull requests merged in 2023-08, with the labels that each got.

#9 8/9까지 숙제 제출합니다.
  problem/programmers/lv1/개인정보 수집 유효기간/김소망.py
  problem/programmers/lv1/다트게임/김소망.py
  problem/programmers/lv1/달리기 경주/김소망.py
  problem/programmers/lv1/로또의 최고 순위와 최저 순위/김소망.py
  problem/programmers/lv1/비밀지도/김소망.py
  problem/programmers/lv1/성격 유형 검사하기/김소망.py
  problem/programmers/lv1/숫자 문자열과 영단어/김소망.py
  problem/programmers/lv1/실패율/김소망.py
  problem/programmers/lv1/추억 점수/김소망.py
  problem/programmers/lv1/카드 뭉치/김소망.py
  problem/programmers/lv1/크레인 인형뽑기 게임/김소망.py
  problem/programmers/lv1/키패드 누르기/김소망.py
  problem/programmers/lv1/폰켓몬/김소망.py
Labels: submit

#12 Big Patch
  README.md
  img/notice/1_1.png
  img/notice/1_2.png
  img/notice/2_1.png
  img/notice/2_2_1.png
  img/notice/3_1_1.png
  img/notice/3_1_2.png
  img/notice/4_1_1.png
  img/notice/4_1_2.png
  img/notice/4_1_3.png
  img/notice/5_1_1.png
  img/notice/5_2_1.png
  img/notice/5_3_1.png
  img/notice/5_4_1.png
  markdown/Notice/HowToUpload.md
  markdown/StudyLog/001.study.md
  markdown/StudyLog/002.study.md
  markdown/StudyLog/003.study.md
  markdown/StudyLog/XXX.study.md
  problem/programmers/lv1/212112
  problem/programmers/lv1/개인정보 수집 유효기간/정광근.py
  problem/programmers/lv1/다트 게임/김소망.py
  problem/programmers/lv1/다트 게임/정광근.py
  problem/programmers/lv1/달리기 경주/정광근.py
  problem/programmers/lv1/로또의 최고 순위와 최저 순위/정광근.py
  problem/programmers/lv1/비밀 지도/김소망.py
  problem/programmers/lv1/비밀 지도/정광근.py
  problem/programmers/lv1/성격 유형 검사하기/정광근.py
  problem/programmers/lv1/숫자 문자열과 영단어/정광근.py
  problem/programmers/lv1/추억 점수/정광근.py
  problem/programmers/lv1/카드 뭉치/정광근.py
  problem/programmers/lv1/키패드 누르기/정광근.py
Labels: submit

#13 Patch And Upload
  README.md
  img/notice/5_5_1.png
  img/notice/6_1_1.png
  img/notice/6_2_1.png
  img/notice/6_3_1.png
  img/notice/6_3_2.png
  markdown/Notice/HowToUpload.md
  markdown/Notice/upload_guide/1.Fork_Origin_Repository.md
  markdown/Notice/upload_guide/2.Clone_the_Forked_Repository.md
  markdown/Notice/upload_guide/3.Commit_your_Assignment.md
  markdown/Notice/upload_guide/4.Push_your_Branch_to_Your_Forked_Repository.md
  markdown/Notice/upload_guide/5.Pull_Request_to_Origin_Repository.md
  markdown/Notice/upload_guide/6.Sync_your_Repository_from_Origin_Repository.md
  markdown/Notice/upload_guide/HowToUpload.md
  markdown/StudyLog/001.study.md
  markdown/StudyLog/002.study.md
  markdown/StudyLog/003.study.md
  problem/programmers/lv1/3진법 뒤집기/조승우.py
  problem/programmers/lv1/개인정보 수집 유효기간/조승.py
  problem/programmers/lv1/기사단원의 무기/조승우.py
  problem/programmers/lv1/다트 게임/조승우.py
  problem/programmers/lv1/달리기 경주/조승우.py
  problem/programmers/lv1/로또의 최고 순위와 최저 순위/조승우.py
  problem/programmers/lv1/비밀 지도/조승우.py
  problem/programmers/lv1/성격 유형 검사하기/조승우.py
  problem/programmers/lv1/숫자 문자열과 영단어/조승우.py
  problem/programmers/lv1/실패율/조승우.py
  problem/programmers/lv1/옹알이(2)/조승우.py
  problem/programmers/lv1/최대공약수와 최소공배수/조승우.py
  problem/programmers/lv1/최소직사각형/조승우.py
  problem/programmers/lv1/추억 점수/조승우.py
  problem/programmers/lv1/카드 뭉치/조승우.py
  problem/programmers/lv1/크기가 작은 부분 문자열/조승우.py
  problem/programmers/lv1/크레인 인형뽑기 게임/조승우.py
  problem/programmers/lv1/키패드 누르기/조승우.py
  problem/programmers/lv1/폰켓몬/조승우.py
  problem/programmers/lv1/햄버거 만들기/조승우.py
Labels: documentation, submit

#15 제출 + 진도표 표기
  markdown/StudyLog/001.study.md
  markdown/StudyLog/002.study.md
  markdown/StudyLog/003.study.md
  problem/programmers/lv1/모의고사/김소망.py
Labels: submit

#16 Today Study
  README.md
  markdown/StudyLog/004.study.md
Labels: documentation

#20 백준 9012 제출합니다.
  problem/boj/s4/9012/김소망.py
Labels: submit

#19 제출합니다.
  problem/boj/s4/9012/정광근.py
Labels: submit

#21 과제 제출이요!
  problem/boj/s4/9012/장지해.py
Labels: submit

#23 과제 제출이요~
  problem/boj/s4/10828/장지해.py
Labels: submit

#24 백준 10828 제출합니다.
  problem/boj/s4/10828/김소망.py
Labels: submit

#25 제출합니다
  markdown/StudyLog/001.study.md
  markdown/StudyLog/002.study.md
  markdown/StudyLog/003.study.md
  markdown/StudyLog/004.study.md
  problem/boj/s2/1874/정광근.py
  problem/boj/s3/1021/정광근.py
  problem/boj/s4/10828/정광근.py
  problem/boj/s4/10845/정광근.py
  problem/boj/s4/10866/정광근.py
  problem/programmers/lv1/같은 숫자는 싫어/정광근.py
  problem/programmers/lv1/기사단원의 무기/정광근.py
  problem/programmers/lv2/올바른 괄호/정광근.cpp
  problem/programmers/lv2/올바른 괄호/정광근.py
Labels: submit
